-- Add more preference columns to buyer_preferences
ALTER TABLE buyer_preferences
ADD COLUMN IF NOT EXISTS wants_ev_charging BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wants_storage BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wants_laundry BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wants_sauna BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wants_sea_view BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS wants_south_facing BOOLEAN DEFAULT FALSE;
